todoism/blueprints/auth.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from faker import Faker
from flask import render_template, redirect, url_for, Blueprint, request, jsonify
from flask_babel import _
from flask_login import login_user, logout_user, login_required, current_user

from todoism.extensions import db
from todoism.models import User, Item

auth_bp = Blueprint('auth', __name__)
fake = Faker()


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('todo.app'))

    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        password = data['password']

        user = User.query.filter_by(username=username).first()

        if user is not None and user.validate_password(password):
            login_user(user)
            return jsonify(message=_('Login success.'))
        return jsonify(message=_('Invalid username or password.')), 400
    return render_template('_login.html')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return jsonify(message=_('Logout success.'))


@auth_bp.route('/register')
def register():
    # generate a random account for demo use
    username = fake.user_name()
    # make sure the generated username was not in database
    while User.query.filter_by(username=username).first() is not None:
        username = fake.user_name()
    password = fake.word()
    user = User(username=username)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    item = Item(body=_('Witness something truly majestic'), author=user)
    item2 = Item(body=_('Help a complete stranger'), author=user)
    item3 = Item(body=_('Drive a motorcycle on the Great Wall of China'), author=user)
    item4 = Item(body=_('Sit on the Great Egyptian Pyramids'), done=True, author=user)
    db.session.add_all([item, item2, item3, item4])
    db.session.commit()

    return jsonify(username=username, password=password, message=_('Generate success.'))

todoism/blueprints/home.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, Blueprint, current_app, make_response, jsonify
from flask_babel import _
from flask_login import current_user

from todoism.extensions import db

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def index():
    return render_template('index.html')


@home_bp.route('/intro')
def intro():
    return render_template('_intro.html')


@home_bp.route('/set-locale/<locale>')
def set_locale(locale):
    if locale not in current_app.config['TODOISM_LOCALES']:
        return jsonify(message=_('Invalid locale.')), 404

    response = make_response(jsonify(message=_('Setting updated.')))
    if current_user.is_authenticated:
        current_user.locale = locale
        db.session.commit()
    else:
        response.set_cookie('locale', locale, max_age=60 * 60 * 24 * 30)
    return response

todoism/blueprints/todo.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, request, Blueprint, jsonify
from flask_babel import _
from flask_login import current_user, login_required

from todoism.extensions import db
from todoism.models import Item

todo_bp = Blueprint('todo', __name__)


@todo_bp.route('/app')
@login_required
def app():
    all_count = Item.query.with_parent(current_user).count()
    active_count = Item.query.with_parent(current_user).filter_by(done=False).count()
    completed_count = Item.query.with_parent(current_user).filter_by(done=True).count()
    return render_template('_app.html', items=current_user.items,
                           all_count=all_count, active_count=active_count, completed_count=completed_count)


@todo_bp.route('/items/new', methods=['POST'])
@login_required
def new_item():
    data = request.get_json()
    if data is None or data['body'].strip() == '':
        return jsonify(message=_('Invalid item body.')), 400
    item = Item(body=data['body'], author=current_user._get_current_object())
    db.session.add(item)
    db.session.commit()
    return jsonify(html=render_template('_item.html', item=item), message='+1')


@todo_bp.route('/item/<int:item_id>/edit', methods=['PUT'])
@login_required
def edit_item(item_id):
    item = Item.query.get_or_404(item_id)
    if current_user != item.author:
        return jsonify(message=_('Permission denied.')), 403

    data = request.get_json()
    if data is None or data['body'].strip() == '':
        return jsonify(message=_('Invalid item body.')), 400
    item.body = data['body']
    db.session.commit()
    return jsonify(message=_('Item updated.'))


@todo_bp.route('/item/<int:item_id>/toggle', methods=['PATCH'])
@login_required
def toggle_item(item_id):
    item = Item.query.get_or_404(item_id)
    if current_user != item.author:
        return jsonify(message=_('Permission denied.')), 403

    item.done = not item.done
    db.session.commit()
    return jsonify(message=_('Item toggled.'))


@todo_bp.route('/item/<int:item_id>/delete', methods=['DELETE'])
@login_required
def delete_item(item_id):
    item = Item.query.get_or_404(item_id)
    if current_user != item.author:
        return jsonify(message=_('Permission denied.')), 403

    db.session.delete(item)
    db.session.commit()
    return jsonify(message=_('Item deleted.'))


@todo_bp.route('/item/clear', methods=['DELETE'])
@login_required
def clear_items():
    items = Item.query.with_parent(current_user).filter_by(done=True).all()
    for item in items:
        db.session.delete(item)
    db.session.commit()
    return jsonify(message=_('All clear!'))

todoism/templates/_app.html
{% extends 'base.html' %}

{% block content %}
    <header class="row">
        <input id="item-input" data-href="{{ url_for('.new_item') }}"
               type="text" placeholder="{{ _('What needs to be done?') }}" autocomplete="off" autofocus required>
    </header>
    <div class="row" id="dashboard">
        <div class="col l9 m12 s12">
            <ul class="tabs">
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="all-item">
                        {{ _('All') }} <span class="grey-text small-text" id="all-count">{{ all_count }}</span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="active-item">
                        {{ _('Active') }} <span class="grey-text small-text" id="active-count">{{ active_count }}</span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="completed-item">
                        {{ _('Done') }} <span class="grey-text small-text"
                                              id="completed-count">{{ completed_count }}</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col l3 hide-on-med-and-down">
            <a class="waves-effect waves-light btn red right" id="clear-btn">
                <i class="material-icons left">clear_all</i>Clear
            </a>
        </div>
    </div>

    <div class="items">
        {% for item in items %}
            {% include '_item.html' %}
        {% endfor %}
    </div>
{% endblock %}

todoism/templates/_intro.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <h2 class="teal-text text-lighten-2">Todoism</h2>
        <h5 class="light">{{ _('We are todoist, we use todoism.') }}</h5>
        <div class="row center-block">
            <div class="fake-browser-ui hoverable card-panel">
                <div class="frame">
                    <span class="red"></span>
                    <span class="blue"></span>
                    <span class="orange"></span>
                </div>
                <img class="responsive-img" src="{{ url_for('static', filename=_('demo.png')) }}">
            </div>
        </div>
        <div class="row">
            <a href="#login" class="btn waves-effect waves-light red">{{ _('Get Started') }}</a>
        </div>
    </div>
{% endblock %}

todoism/templates/_item.html
<div class="row item card-panel hoverable" data-href="{{ url_for('.edit_item', item_id=item.id) }}"
     data-id="{{ item.id }}" data-body="{{ item.body }}" data-done={{ item.done|tojson }}>
    <span class="item-body">
        <a class="button done-btn" data-href="{{ url_for('.toggle_item', item_id=item.id) }}">
            <i class="material-icons left">{% if item.done %}check_box{% else %}check_box_outline_blank{% endif %}</i>
        </a>
        <span class="{% if item.done %}inactive-item{% else %}active-item{% endif %}"
              id="body{{ item.id }}">{{ item.body }}</span>
    </span>
    <span class="hide edit-btns right">
        <a class="right button delete-btn" data-href="{{ url_for('.delete_item', item_id=item.id) }}">
            <i class="material-icons small-icon left">clear</i>
        </a>
        <a class="right button edit-btn">
            <i class="material-icons small-icon left">mode_edit</i>
        </a>
    </span>
</div>

todoism/templates/_login.html
{% extends 'base.html' %}

{% block content %}
    <header class="center">
        <h4 class="red-text">{{ _('Login on Todoism') }}</h4><br>
    </header>
    <div class="login-form">
        <input class="validate login-input" id="username-input" name="username" type="text" placeholder="Username"
               autofocus required>
        <input class="validate login-input" id="password-input" name="password" type="password" placeholder="Password"
               required>
        <span class="right">
            <a class="btn grey" id="register-btn">{{ _('Get a test account') }}</a>
            <a class="btn red" id="login-btn">{{ _('Login') }}</a>
        </span>
        <p><a class="blue-text link button left" id="toggle-password">{{ _('Toggle Password') }}</a></p>&nbsp;
    </div>
{% endblock %}

todoism/templates/base.html
<nav class="red lighten-2" role="navigation">
    <div class="nav-wrapper container">
        <a href="#intro" class="brand-logo">Promise</a>
        <a data-target="nav-mobile" class="sidenav-trigger button"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            {% if current_user.is_authenticated %}
                <li>
                    <a class="waves-effect waves-light btn orange" href="#app">{{ current_user.username }}
                        <span class="badge new" id="active-count-nav">{{ active_items }}</span>
                    </a>
                </li>
                <li>
                    <a class="waves-effect waves-light" id="logout-btn" data-href="{{ url_for('auth.logout') }}">
                        <i class="material-icons">power_settings_new</i>
                    </a>
                </li>
            {% else %}
                <li><a class="waves-effect waves-light btn red" href="#login">{{ _('Login') }}</a></li>
            {% endif %}
            <li>
                <a class="waves-effect waves-light dropdown-trigger" id="locale-dropdown-btn" data-target="locale-dropdown">
                    <i class="material-icons">language</i>
                </a>
            </li>
        </ul>
    </div>
</nav>

<ul id="nav-mobile" class="sidenav">
    {% if current_user.is_authenticated %}
        <li><a class="waves-effect waves-light btn red clear-btn sidenav-close">Clear</a></li>
        <li><a class="waves-effect waves-light btn orange sidenav-close" id="app-btn"
               href="#app">{{ current_user.username }}</a>
        </li>
        <li><a class="waves-effect waves-light btn grey sidenav-close" id="logout-btn"
               data-href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
    {% else %}
        <li><a class="waves-effect waves-light btn red sidenav-close" href="#login">{{ _('Login') }}</a></li>
    {% endif %}
</ul>

<ul id="locale-dropdown" class="dropdown-content">
    <li><a class="lang-btn" data-href="{{ url_for('home.set_locale', locale='zh_Hans_CN') }}">简体中文</a></li>
    <li><a class="lang-btn" data-href="{{ url_for('home.set_locale', locale='en_US') }}">English</a></li>
</ul>

<main>
    {% block content %}{% endblock %}
</main>
<footer class="center">
    <small> &copy; 2018 <a class="blue-text link" href="http://greyli.com" title="Written by Grey Li">Grey Li</a> -
        <a class="blue-text link" href="https://github.com/greyli/todoism" title="Fork me on GitHub">GitHub</a> -
        <a class="blue-text link" href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
    </small>
</footer>

todoism/templates/errors.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Error {{ code }} - Todoism</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
</head>

<body>
<main>
    <header class="center">
        <h4 class="red-text">Todoism</h4>
    </header>
    <div class="row card-panel hoverable">
        <span class="col s10">
            <span class="active-item">{{ code }} - {{ info }}</span>
        </span>
        <span class="col s2">
            <a class="button right" href="{{ url_for('home.index') }}">{{ _('Back Home') }}</a>
        </span>
    </div>
</main>
</body>
</html>

todoism/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Promise</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div id="main"></div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
    var login_page_url = "{{ url_for('auth.login') }}";
    var app_page_url = "{{ url_for('todo.app') }}";
    var intro_page_url = "{{ url_for('home.intro') }}";
    var new_item_url = "{{ url_for('todo.new_item') }}";
    var clear_item_url = "{{ url_for('todo.clear_items') }}";
    var login_url = "{{ url_for('auth.login') }}";
    var register_url = "{{ url_for('auth.register') }}";
    var logout_url = "{{ url_for('auth.logout') }}";
    var default_error_message = "{{ _('Oops, something was wrong!') }}";
    var empty_body_error_message = "{{ _('Your todo was empty!') }}";
    var login_error_message = "{{ _('Empty username or password!') }}";
</script>
</body>
</html>